#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

snake_game="$cmd_dir/run_snake_evolution"

echo "Running Snake Evolution game..."
$snake_game || panic "hello program failed"



