#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine current directory"

snake_game_loc="$cmd_dir/run_snake_evolution"

echo "Running Snake Evolution game..."
$snake_game_loc || panic "Running Snake Evolution failed"



